(() => {
  const clusters=[...document.querySelectorAll(".cluster")],names=[["Threshold","Protocols","Invisible Layers","Signal","Residue","Territory"],["Interference","Assembly","Feedback","Proximity","Translation","Topology"],["Atlas","Machine Vision","Terrain 01","Archive Tool","Non-map","Open Field"]],arts=["rings","lines","grid","signal","dots","blocks"];
  clusters.forEach((cluster,c)=>names[c].forEach((name,i)=>{const card=document.createElement("button");card.className=`card ${i%3===1?"dark":i%3===0?"acid":""}`;card.dataset.code=`${"ABC"[c]}—0${i+1}`;card.dataset.title=name;card.innerHTML=`<small>0${i+1}</small><span class="art ${arts[(i+c)%arts.length]}"></span><strong>${name}</strong><em>${cluster.dataset.name} / 2026</em>`;cluster.append(card)}));
  const viewport=document.querySelector("#viewport"),world=document.querySelector("#world"),canvas=document.querySelector("#space"),ctx=canvas.getContext("2d"),coords=document.querySelector("#coords"),intro=document.querySelector(".intro"),detail=document.querySelector("#detail"),about=document.querySelector("#about"),nav=[...document.querySelectorAll("[data-view]")],state={rx:-5,ry:-16,z:.72,trx:-5,try:-16,tz:.72,drag:false,x:0,y:0,moved:false},views={a:[-4,-18,.86],b:[-7,-1,.86],c:[-4,17,.86]};
  function resize(){const d=Math.min(devicePixelRatio,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle="#11120f28";const g=innerWidth<600?38:52;for(let y=86;y<innerHeight;y+=g)for(let x=24;x<innerWidth;x+=g){ctx.beginPath();ctx.arc(x+Math.sin(y*.018)*9,y,.65,0,7);ctx.fill()}}
  function render(){state.rx+=(state.trx-state.rx)*.09;state.ry+=(state.try-state.ry)*.09;state.z+=(state.tz-state.z)*.09;world.style.transform=`scale(${state.z}) rotateX(${state.rx}deg) rotateY(${state.ry}deg)`;coords.textContent=`ORBIT / ${String(Math.round(state.ry+360)%360).padStart(3,"0")}°   TILT / ${String(Math.abs(Math.round(state.rx))).padStart(3,"0")}°`;requestAnimationFrame(render)}
  viewport.onpointerdown=e=>{if(e.target.closest("button,a,aside"))return;state.drag=true;state.moved=false;state.x=e.clientX;state.y=e.clientY;viewport.classList.add("drag")};viewport.onpointermove=e=>{if(!state.drag)return;let dx=e.clientX-state.x,dy=e.clientY-state.y;if(Math.abs(dx)+Math.abs(dy)>2)state.moved=true;state.try+=dx*.11;state.trx=Math.max(-36,Math.min(30,state.trx-dy*.08));state.x=e.clientX;state.y=e.clientY;intro.style.opacity=".15";nav.forEach(b=>b.classList.remove("active"))};onpointerup=()=>{state.drag=false;viewport.classList.remove("drag")};viewport.onwheel=e=>{e.preventDefault();state.tz=Math.max(.45,Math.min(1.35,state.tz-e.deltaY*.0007))};
  nav.forEach(b=>b.onclick=()=>{[state.trx,state.try,state.tz]=views[b.dataset.view];intro.style.opacity=".15";nav.forEach(x=>x.classList.toggle("active",x===b))});document.querySelectorAll(".card").forEach(card=>card.onclick=()=>{if(state.moved)return;detail.querySelector(".code").textContent=`${card.dataset.code} / MATERIAL`;detail.querySelector("h2").textContent=card.dataset.title;detail.classList.add("open");about.classList.remove("open")});detail.querySelector(".close").onclick=()=>detail.classList.remove("open");document.querySelector("#aboutBtn").onclick=()=>{about.classList.toggle("open");detail.classList.remove("open")};document.querySelector(".logo").onclick=e=>{e.preventDefault();Object.assign(state,{trx:-5,try:-16,tz:.72});intro.style.opacity=1};
  onkeydown=e=>{if(e.key==="ArrowLeft")state.try-=7;if(e.key==="ArrowRight")state.try+=7;if(e.key==="ArrowUp")state.trx+=5;if(e.key==="ArrowDown")state.trx-=5;if(e.key==="+"||e.key==="=")state.tz+=.1;if(e.key==="-")state.tz-=.1;if(e.key==="Escape"){detail.classList.remove("open");about.classList.remove("open")}};onresize=resize;resize();render();
})();
